# Generated by Django 5.1 on 2024-08-29 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_question_set_question_quiz_delete_questionset'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='answer',
            name='is_late',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='answer',
            name='start_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
